/* Run aarch64-linux ELF binaries on macOS Apple Silicon
 *
 * Copyright 2026 elfuse contributors
 * Copyright 2025 Moritz Angermann, zw3rk pte. ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Uses Hypervisor.framework to create a lightweight VM with:
 *   - A minimal EL1 shim (embedded as shim_blob.h) that provides exception
 *     vectors and forwards SVC #0 (Linux syscalls) to the host via HVC #5.
 *   - All system registers configured from the host before vCPU start.
 *   - Guest memory identity-mapped at GVA=GPA with 2MiB block page tables.
 *   - Syscall handlers that translate Linux syscalls to macOS equivalents.
 *
 * Usage: elfuse [--verbose] [--timeout N] [--sysroot PATH] <elf-path> [args...]
 */

#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "core/bootstrap.h"
#include "core/guest.h"

#include "runtime/forkipc.h"
#include "runtime/proctitle.h"

#include "syscall/proc.h"

#include "debug/gdbstub.h"
#include "debug/log.h"

static int parse_int_arg(const char *s, int min, int max, int *out)
{
    char *end = NULL;
    errno = 0;
    long value = strtol(s, &end, 10);
    if (errno != 0 || end == s || *end != '\0' || value < min || value > max)
        return -1;
    *out = (int) value;
    return 0;
}

static void free_guest_argv(const char **guest_argv, int guest_argc)
{
    if (!guest_argv)
        return;
    for (int i = 0; i < guest_argc; i++)
        free((void *) guest_argv[i]);
    free((void *) guest_argv);
}

static void cleanup_main_resources(guest_t *g,
                                   bool guest_initialized,
                                   const char **guest_argv,
                                   int guest_argc,
                                   const char *elf_path,
                                   const char *sysroot_path)
{
    if (guest_initialized)
        guest_destroy(g);
    free_guest_argv(guest_argv, guest_argc);
    free((void *) elf_path);
    free((void *) sysroot_path);
}

/* Embedded shim binary (generated by xxd -i from shim.bin) */
#include "shim_blob.h"

/* Build-time version string (generated by make into build/version.h) */
#include "version.h"

/* Verify the host CPU's DC ZVA granule matches the shim's hardcoded value.
 *
 * DCZID_EL0 is readable from EL0 without trapping, so guest libc reads the
 * host's value directly and uses it as the stride for memset(0) loops. The
 * shim emulates each trapped DC ZVA by zeroing exactly 64 bytes
 * (src/core/shim.S). Apple Silicon M1..M4 report DCZID_EL0.BS=4 (64 bytes);
 * any future host that advertises a different granule would cause silent
 * partial-zero corruption of guest memory. Abort here so the mismatch
 * surfaces at startup instead of as data corruption later.
 */
static int host_dc_zva_assert(void)
{
    uint64_t dczid;
    __asm__ volatile("mrs %0, DCZID_EL0" : "=r"(dczid));
    if (dczid & (1ULL << 4)) {
        log_error(
            "host CPU prohibits DC ZVA (DCZID_EL0.DZP=1); cannot run "
            "guests that depend on it");
        return -1;
    }
    unsigned bs = (unsigned) (dczid & 0xF);
    if (bs != 4) {
        log_error(
            "host DCZID_EL0.BS=%u (%u-byte DC ZVA block) but the shim "
            "emulates 64 bytes; update src/core/shim.S before running",
            bs, 1u << (bs + 2));
        return -1;
    }
    return 0;
}

int main(int argc, char **argv)
{
    log_init();

    bool verbose = false;
    int timeout_sec = 10, fork_child_fd = -1, vfork_notify_fd = -1;
    const char *sysroot = NULL;
    int gdb_port = 0;
    bool gdb_stop_on_entry = false;
    int arg_start = 1;

    /* --help and --version do not require an ELF path. */
    if (argc > 1) {
        if (!strcmp(argv[1], "--version") || !strcmp(argv[1], "-V")) {
            printf("elfuse %s\n", ELFUSE_VERSION);
            return 0;
        }
        if (!strcmp(argv[1], "--help") || !strcmp(argv[1], "-h")) {
            printf(
                "usage: elfuse [--verbose] [--timeout N] [--sysroot PATH]\n"
                "              [--gdb PORT] [--gdb-stop-on-entry]\n"
                "              <elf-path> [args...]\n"
                "\n"
                "Options:\n"
                "  -h, --help              Show this help and exit\n"
                "  -V, --version           Show version and exit\n"
                "  -v, --verbose           Trace each guest syscall\n"
                "  --timeout N             Per-iteration vCPU run timeout "
                "(seconds, default 10; 0 disables)\n"
                "  --sysroot PATH          Resolve absolute guest paths under "
                "PATH first\n"
                "  --gdb PORT              Listen for GDB Remote Serial "
                "Protocol on PORT\n"
                "  --gdb-stop-on-entry     Halt before the first guest "
                "instruction\n");
            return 0;
        }
    }

    if (host_dc_zva_assert() < 0)
        return 1;

    /* Parse elfuse options until the first guest argv element. */
    while (arg_start < argc && argv[arg_start][0] == '-') {
        if (!strcmp(argv[arg_start], "--verbose") ||
            !strcmp(argv[arg_start], "-v")) {
            verbose = true;
            log_set_level(LOG_DEBUG);
            arg_start++;
        } else if ((!strcmp(argv[arg_start], "--timeout") ||
                    !strcmp(argv[arg_start], "-t")) &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX, &timeout_sec) <
                0)
                timeout_sec = 10;
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--fork-child") &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX, &fork_child_fd) <
                0) {
                log_error("invalid fork child fd: %s", argv[arg_start + 1]);
                return 1;
            }
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--vfork-notify-fd") &&
                   arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 0, INT_MAX,
                              &vfork_notify_fd) < 0) {
                log_error("invalid vfork notify fd: %s", argv[arg_start + 1]);
                return 1;
            }
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--sysroot") &&
                   arg_start + 1 < argc) {
            sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--gdb") && arg_start + 1 < argc) {
            if (parse_int_arg(argv[arg_start + 1], 1, 65535, &gdb_port) < 0) {
                log_error("invalid GDB port: %s", argv[arg_start + 1]);
                return 1;
            }
            if (!verbose)
                log_set_level(LOG_INFO);
            arg_start += 2;
        } else if (!strcmp(argv[arg_start], "--gdb-stop-on-entry")) {
            gdb_stop_on_entry = true;
            arg_start++;
        } else if (!strcmp(argv[arg_start], "--")) {
            arg_start++;
            break;
        } else {
            log_error("unknown option: %s", argv[arg_start]);
            log_error(
                "usage: elfuse [--verbose] [--timeout N] "
                "[--sysroot PATH] [--gdb PORT] "
                "[--gdb-stop-on-entry] <elf-path> [args...]");
            return 1;
        }
    }

    /* Fork-child mode: receive VM state over IPC and run */
    if (fork_child_fd >= 0)
        return fork_child_main(fork_child_fd, vfork_notify_fd, verbose,
                               timeout_sec);

    if (arg_start >= argc) {
        log_error(
            "usage: elfuse [--verbose] [--timeout N] "
            "[--sysroot PATH] <elf-path> [args...]");
        return 1;
    }

    /* Copy elf_path and guest_argv to heap because the original argv string
     * data lives in a contiguous stack region that elfuse clobbers below for
     * the process title (PostgreSQL/nginx argv-clobber technique).
     */
    const char *elf_path = strdup(argv[arg_start]);
    bool have_sysroot = (sysroot != NULL);
    const char *sysroot_path = have_sysroot ? strdup(sysroot) : NULL;
    sysroot = sysroot_path;
    int guest_argc = argc - arg_start;
    const char **guest_argv =
        (const char **) calloc((size_t) guest_argc, sizeof(char *));
    guest_t g;
    bool guest_initialized = false;
    if (!elf_path || (have_sysroot && !sysroot_path) || !guest_argv) {
        log_error("out of memory");
        cleanup_main_resources(&g, guest_initialized, guest_argv, guest_argc,
                               elf_path, sysroot_path);
        return 1;
    }
    for (int i = 0; i < guest_argc; i++) {
        guest_argv[i] = strdup(argv[arg_start + i]);
        if (!guest_argv[i]) {
            log_error("out of memory");
            cleanup_main_resources(&g, guest_initialized, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            return 1;
        }
    }

    guest_bootstrap_t boot;
    extern char **environ;

    if (guest_bootstrap_prepare(&g, elf_path, sysroot, guest_argc, guest_argv,
                                environ, shim_bin, shim_bin_len, verbose,
                                &guest_initialized, &boot) < 0) {
        cleanup_main_resources(&g, guest_initialized, guest_argv, guest_argc,
                               elf_path, sysroot_path);
        return 1;
    }

    runtime_set_process_title(argc, argv, elf_path);

    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    if (guest_bootstrap_create_vcpu(&g, &boot, verbose, &vcpu, &vexit) < 0) {
        cleanup_main_resources(&g, guest_initialized, guest_argv, guest_argc,
                               elf_path, sysroot_path);
        return 1;
    }

    /* GDB setup must happen before the first run so entry-stop and hardware
     * breakpoints can affect the initial vCPU.
     */
    if (gdb_port > 0) {
        if (gdb_stub_init(gdb_port, &g) < 0) {
            log_error("failed to initialize GDB stub");
            cleanup_main_resources(&g, guest_initialized, guest_argv,
                                   guest_argc, elf_path, sysroot_path);
            return 1;
        }
        /* Mirror any preconfigured breakpoints/watchpoints into this vCPU. */
        gdb_stub_sync_debug_regs(vcpu);

        if (gdb_stop_on_entry)
            gdb_stub_wait_for_attach();
    }

    /* vcpu_run_loop owns guest execution until exit, fatal signal, or timeout.
     */
    int exit_code = vcpu_run_loop(vcpu, vexit, &g, verbose, timeout_sec);

    /* Tear down debugger state before freeing guest/vCPU resources. */
    gdb_stub_shutdown();
    cleanup_main_resources(&g, guest_initialized, guest_argv, guest_argc,
                           elf_path, sysroot_path);

    return exit_code;
}
